version: '3.9'

services:
  student-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: student-app
    ports:
      - '3333:3333'
    environment:
      - PORT=3333
      - NODE_ENV=production
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173
    restart: unless-stopped
